// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://matoxpgrcghiepicwbnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hdG94cGdyY2doaWVwaWN3Ym54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyOTk0MjUsImV4cCI6MjA1NDg3NTQyNX0.Pk45EcXursvxak1iY_DRpa0D2noxz6xOOkNAOHMY5_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);